### ISSUE TITLE
A question about datasets.

### ISSUE THREAD

**Issue by Sample-design-alt** [mims-harvard/UniTS#2]
Awesome work! 
I am interesting for your work! But I have some problems for datasets.
1. What the datasets are you used? UCR and Monash? anything else? Is table 7 the full data set listed?
2. Do you have a dataset that uses anomaly detection? The paper mentions using 38 datasets, and Table 7 is supposed to list all of them, so I don't think you should be using the anomaly detection dataset. 
3. I have a doubt for the dataset, why not use more datasets then. I think more datasets will help the model to improve the performance.
Finally, I desire to know how many GPU were used for training. 

Thanks for your contributions!

**Comment by gasvn** [comment]
Thank you for your interest in our work!
Regarding your question:
1. Yes, table7 is the dataset used for multi-task setting. For other task setting, we includes more datasets which can also be found in the paper.
2. Our method support anomaly detection. As we mentioned in the paper, we test the few shot anomaly detection performance on anomaly detection datasets. During the multi-task training, we didn't include anomaly detection datasets because we want to test the out-of-domain task performance.
3. The only reason for now using more dataset is that we need to meet the ddl for conference submission, so we don't have enought time to do so before ddl. We are collecting a larger dataset and plan to train a larger model with more data.
4. For now, we use 1-4 gpus to train the model depanding on different training settings.

(Maybe you can check the commit log of this repo to find out more details about our code, as the code is still under a internal administrative review)

**Comment by Sample-design-alt** [comment]
Sound interesting!  Thanks for you reply!
1. Actually, I'm still confused for the few shot learning. The paper mentioned that ` UNITS pretrained on \mathcal{X}, can be fine-tuned on a few samples on new data \mathcal{\tile{X}} and \mathcal{\tile{Y}} ...' , but the experiment details does not mention the settings about few-shot (e.g., 5-way 1-shot). Maybe there are some misunderstanding about few-shot learning for me. 
2. Could you please tell me the gpu type? 80G A100?

**Comment by gasvn** [comment]
1. In few-shot, we use 5%-10% of the full training set to finetune the model.
2. We use 40G A100 GPU.
